package com.myErp.utils;
import java.text.SimpleDateFormat;

public class GlobalsConstant {
	 public static final String CHARSET = "UTF-8";
	  public static final String TaskDeliveryUrl = "http://task.91sph.com";
	  public static final String EMP_HOME = "/self/";
	  public static final String MAIN_HOME = "/main/";
	  public static final String INDEX = "/";
//	  public static final String CONSLOE_DOMAIN_NAME = Resources.getConfigString("console.domain");
//	  public static final String PIC_DOMAIN_NAME = Resources.getConfigString("pic.domain");
//	  public static final String M_SITE_DOMAIN_NAME = Resources.getConfigString("m.domain");
	  public static final String SAFE_KEY = "saftkey";
	  public static final String EMP_SESSION_KEY = "xsUserSession";
	  public static final String UPDATE_WALLET_VALID_CODE = "walletValidCode";
	  public static final String ERROR_KEY = "error";
	  public static final char SEPARATOR = ',';
	  public static final int USER_STATE_BLACKLIST = 20;
	  public static final String FACE_KEY = "face_key";
	  public static final int STATE_DEL = -1;
	  public static final int STATE_NORMAL = 1;
	  public static final int STATE_NEW = 1;
	  public static final Integer SUPER_ROLE = Integer.valueOf(1);
	  public static final String FILE_PIC_SUFFIX = "jpg,png,gif,bmp,jpeg";
	  public static SimpleDateFormat DF_YYMMDD_HHMMSS = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	  public static SimpleDateFormat DF_YYMMDD = new SimpleDateFormat("yyyy-MM-dd");
	  public static SimpleDateFormat DF_YYMMDDSTR = new SimpleDateFormat("yyyyMMdd");
	  public static final String FTP_CONFIG_KEY = "ftp_config";
	  public static final String METHOD_GET = "get";
	  public static final long IMAGE_MAX_SIZE = 4194304L;
	  public static final int PBIZ_STYPE_CODE = 1;
	  public static final int PBIZ_BTYPE_CODE = 2;
	  public static final int BIZ_TYPE_BC = 10;
	  public static final int BIZ_TYPE_EC = 50;
	  public static final int BIZ_TYPE_APC = 8;
	  public static final int BIZ_TYPE_CC = 5;
	  public static final int BIZ_TYPE_CS = 201;
	  public static final int MAIN_STATE_REFUND = 40;
	  public static final int DEFAULT_DATE_LONG = -30;
	  public static final int PAYOUT_PAY_SUCESS = 2;
	  public static final int PAYOUT_PAY_ERROR = -1;
	  public static final int REFUND_TYPE_FULL = 1;
	  public static final int REFUND_TYPE_PART = 2;
	  public static final int APP_STATE_FINISH = 8;
	  public static final int APP_STATE_CLOSE = 10;
	  public static final int ORDER_STATE_RFFUND = 84;
	  public static final int ORDER_STATE_CLOSE = 40;
	  public static final int ORDER_STATE_FINISH = 34;
	  public static final int DELIVERY_TYPE_SEND = 1;
	  public static final int DELIVERY_TYPE_REC = 2;
}
